// A list of common English words for fallback text generation.
export const commonWords = [
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'I', 'it', 'for', 'not', 'on', 'with', 'he',
  'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or',
  'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if', 'about',
  'who', 'get', 'which', 'go', 'me', 'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know',
  'take', 'person', 'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than',
  'then', 'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also', 'back', 'after', 'use', 'two',
  'how', 'our', 'work', 'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these',
  'give', 'day', 'most', 'us', 'is', 'are', 'was', 'were', 'has', 'had', 'does', 'did', 'said', 'goes',
  'went', 'made', 'makes', 'making', 'came', 'comes', 'coming', 'took', 'takes', 'taking', 'got',
  'gets', 'getting', 'seen', 'sees', 'seeing', 'knew', 'knows', 'knowing', 'thought', 'thinks',
  'thinking', 'told', 'tells', 'telling', 'used', 'uses', 'using', 'found', 'finds', 'finding',
  'gave', 'gives', 'giving', 'worked', 'works', 'working', 'called', 'calls', 'calling', 'tried',
  'tries', 'trying', 'asked', 'asks', 'asking', 'needed', 'needs', 'needing', 'felt', 'feels',
  'feeling', 'became', 'becomes', 'becoming', 'left', 'leaves', 'leaving', 'put', 'puts', 'putting',
  'meant', 'means', 'meaning', 'kept', 'keeps', 'keeping', 'let', 'lets', 'letting', 'began',
  'begins', 'beginning', 'seemed', 'seems', 'seeming', 'helped', 'helps', 'helping', 'talked',
  'talks', 'talking', 'turned', 'turns', 'turning', 'started', 'starts', 'starting', 'showed',
  'shows', 'showing', 'heard', 'hears', 'hearing', 'played', 'plays', 'playing', 'ran', 'runs',
  'running', 'moved', 'moves', 'moving', 'lived', 'lives', 'living', 'believed', 'believes',
  'believing', 'brought', 'brings', 'bringing', 'happened', 'happens', 'happening', 'wrote',
  'writes', 'writing', 'provided', 'provides', 'providing', 'sat', 'sits', 'sitting', 'stood',
  'stands', 'standing', 'lost', 'loses', 'losing', 'paid', 'pays', 'paying', 'met', 'meets',
  'meeting', 'included', 'includes', 'including', 'continued', 'continues', 'continuing', 'set',
  'sets', 'setting', 'learned', 'learns', 'learning', 'changed', 'changes', 'changing', 'led',
  'leads', 'leading', 'understood', 'understands', 'understanding', 'watched', 'watches',
  'watching', 'followed', 'follows', 'following', 'stopped', 'stops', 'stopping', 'created',
  'creates', 'creating', 'spoke', 'speaks', 'speaking', 'read', 'reads', 'reading', 'allowed',
  'allows', 'allowing', 'added', 'adds', 'adding', 'spent', 'spends', 'spending', 'grew', 'grows',
  'growing', 'opened', 'opens', 'opening', 'walked', 'walks', 'walking', 'won', 'wins', 'winning',
  'offered', 'offers', 'offering', 'remembered', 'remembers', 'remembering', 'loved', 'loves',
  'loving', 'considered', 'considers', 'considering', 'appeared', 'appears', 'appearing', 'bought',
  'buys', 'buying', 'waited', 'waits', 'waiting', 'served', 'serves', 'serving', 'died', 'dies',
  'dying', 'sent', 'sends', 'sending', 'expected', 'expects', 'expecting', 'built', 'builds',
  'building', 'stayed', 'stays', 'staying', 'fell', 'falls', 'falling', 'cut', 'cuts', 'cutting',
  'reached', 'reaches', 'reaching', 'killed', 'kills', 'killing', 'raised', 'raises', 'raising',
  'passed', 'passes', 'passing', 'sold', 'sells', 'selling', 'decided', 'decides', 'deciding',
  'returned', 'returns', 'returning', 'explained', 'explains', 'explaining', 'hoped', 'hopes',
  'hoping', 'developed', 'develops', 'developing', 'carried', 'carries', 'carrying', 'broke',
  'breaks', 'breaking', 'received', 'receives', 'receiving', 'agreed', 'agrees', 'agreeing',
  'supported', 'supports', 'supporting', 'hit', 'hits', 'hitting', 'produced', 'produces',
  'producing', 'ate', 'eats', 'eating', 'covered', 'covers', 'covering', 'caught', 'catches',
  'catching', 'drew', 'draws', 'drawing', 'chose', 'chooses', 'choosing', 'people', 'history',
  'way', 'art', 'world', 'information', 'map', 'two', 'family', 'government', 'health', 'system',
  'computer', 'meat', 'year', 'thanks', 'music', 'person', 'reading', 'method', 'data', 'food',
  'understanding', 'theory', 'law', 'bird', 'literature', 'problem', 'software', 'control',
  'knowledge', 'power', 'ability', 'economics', 'love', 'internet', 'television', 'science',
  'library', 'nature', 'fact', 'product', 'idea', 'temperature', 'investment', 'area', 'society',
  'activity', 'story', 'industry', 'media', 'thing', 'oven', 'community', 'definition', 'safety',
  'quality', 'development', 'language', 'management', 'player', 'variety', 'video', 'week',
  'security', 'country', 'exam', 'movie', 'organization', 'equipment', 'physics', 'analysis',
  'policy', 'series', 'thought', 'basis', 'boyfriend', 'direction', 'strategy', 'technology',
  'army', 'camera', 'freedom', 'paper', 'environment', 'child', 'instance', 'month', 'truth',
  'marketing', 'university', 'writing', 'article', 'department', 'difference', 'goal', 'news',
  'audience', 'fishing', 'growth', 'income', 'marriage', 'user', 'combination', 'failure',
  'meaning', 'medicine', 'philosophy', 'teacher', 'communication', 'night', 'chemistry',
  'disease', 'disk', 'energy', 'nation', 'road', 'role', 'soup', 'advertising', 'location',
  'success', 'addition', 'apartment', 'education', 'math', 'moment', 'painting', 'politics',
  'attention', 'decision', 'event', 'property', 'shopping', 'student', 'wood', 'competition',
  'distribution', 'entertainment', 'office', 'population', 'president', 'unit', 'category',
  'cigarette', 'context', 'introduction', 'opportunity', 'performance', 'driver', 'flight',
  'length', 'magazine', 'newspaper', 'relationship', 'teaching', 'cell', 'dealer', 'finding',
  'lake', 'member', 'message', 'phone', 'scene', 'appearance', 'association', 'concept',
  'customer', 'death', 'discussion', 'housing', 'inflation', 'insurance', 'mood', 'woman',
];
